### PR TITLE
Adapt service script location to match PATH

### PR DESCRIPTION
**Pull request by elcajon**
# Proposed Changes

I found out by accident in the Debian based Code-Server add-on that the custom s6 service script is not found via $PATH.

The underlying Debian image comes with the init.d service script
```bash
which service                                                                                                    
/usr/sbin/service
```

```bash
echo $PATH        
/usr/local/lib/code-server/lib/vscode/bin/remote-cli:/command:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

For the custom s6 service script to be found instead of the init.d one I would recommend moving it to `/usr/local/sbin` 

Also not relevant for the Alpine base image.

Probably not too urgent since no one has noticed it yet. 😉 

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by frenck** [comment]
Why does it matter?

**Comment by elcajon** [comment]
I admit that the use of the script is generally quite limited in the add-ons environment.

If the script would be in the path before the init.d standard script it would be callable via Bash/Zsh. Of course, the script can be called that way by specifying the full path. 

My use case (which is why I stumbled across the "problem") is that I installed `cron` in the code server add-on to automate backups via `rclone` and created another "custom" s6 service (via `init_commands`) which I wanted to start via this script.

**Comment by frenck** [comment]
> I admit that the use of the script is generally quite limited in the add-ons environment.

It is there for development purposes (and in the past, it had use cases for some application calling services to restart parts).

It is not meant for direct user consumption.

> My use case (which is why I stumbled across the "problem") is that I installed cron in the code server add-on to automate backups via rclone and created another "custom" s6 service (via init_commands) which I wanted to start via this script.

Exactly why it isn't there :0

**Comment by elcajon** [comment]
In that case, it's a done deal. I was not sure if it does not work on purpose or by chance 😉 

> Exactly why it isn't there :0

Fortunately, it still works if the complete path is known. 

Then I close this and wish you a nice rest of the weekend

**Comment by frenck** [comment]
> Then I close this and wish you a nice rest of the weekend

You too! ❤️

**Pull request closed without merging**
