### PR TITLE
Upgrade bashio to v0.7.1

### PR DESCRIPTION
**Pull request by andygrunwald**
# Proposed Changes

Upgrade bashio to v0.7.1 to up to date.

### CODE REVIEW

**Comment by frenck** [comment]
Thank you, for helping, but this is not enough and not that easy.

**Comment by andygrunwald** [comment]
@frenck Thanks for looking at this.
Can you elaborate on what is missing?

**Comment by frenck** [comment]
For starters, this is a drive-by PR (as it is called). Done from the browser.
Bashio has backward-incompatible changes, the fact this is a drive-by PR and the backward changes are not handled, makes this PR untested and incomplete.

That is not helping, but adding a risk. Hence, me closing.

**Comment by andygrunwald** [comment]
That adds more context to it. Thanks.

**Pull request closed without merging**
