### PR TITLE
Fix intermittent `unable to s6_svstatus_read` error

### PR DESCRIPTION
**Pull request by felipecrs**
# Proposed Changes

Fixes intermittent s6-overlay error that prevents add-ons from starting.

## Related Issues

- https://github.com/home-assistant/docker-base/pull/193
- https://github.com/home-assistant/core/issues/79976
- https://github.com/home-assistant/core/pull/82527
- https://github.com/just-containers/s6-overlay/issues/460

### CODE REVIEW

**Comment by frenck** [comment]
Let's make sure we communicate this with the S6-overlay project first. Since this issue is rather old, I don't think there is a rush in adding this.

Therefore, I'll hold this until the upstream maintainer is aware and gets his question answered, as pointed out here:

https://github.com/home-assistant/core/pull/82527#issuecomment-1326458950

ref: <https://github.com/just-containers/s6-overlay/issues/460#issuecomment-1174860109>

As it is better to have better default upstream than every project by itself running into similar problems and trying to solve them on its own.


../Frenck

**Comment by felipecrs** [comment]
Based on https://github.com/home-assistant/core/pull/82527#issuecomment-1326915919 I think this can now be merged.

**Comment by frenck** [comment]
See my comment above.

**Comment by felipecrs** [comment]
Cancelling in because of https://github.com/home-assistant/docker-base/pull/193#issuecomment-1328066148.

**Pull request closed without merging**
